title: Tabletop Game Note
author: pecan7uts
url: https://pecan7uts.github.io # root address of the site
description: > # description of the site (multiple lines allowed)
  ボードゲーム関連のメモやファイル置き場です

permalink: date

favicon: "./avatar.png" # relative path to site's favicon
logo: "./avatar.png"
locale: ja

twitter:
    username: pecan7uts # update or delete this
    card: summary_large_image

#theme: moonwalk # if you are using GitHub Pages, change it to remote_theme: abhinavs/moonwalk
remote_theme: abhinavs/moonwalk

theme_config:
  appearance: "dark" # can be "light", "dark" or "auto"
  appearance_toggle: false # if appearance can be switched by user
  back_home_text: "Home.." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description
  show_navbar: true # show horizontal navbar
  show_footer: true # show footer links in home page,add in _data/home.yml
  show_copyright: true # show copyright notice in footer
  # following keys are using to create home layout
  show_projects: true # show projects as cards, add in _data/home.yml
  show_blog: true # show blog posts added in _posts
  show_old_projects: false # show old projects as cards, add in _data/home.yml
  show_misc_list: false # show generic vertical list for misc details, add _data/home.yml
  # options for "home" page
  home:
    title_projects: Pinned
    title_misc_list: Details
    title_blog: Blog
    title_old_projects: 古めの記事

soopr:
  publish_token: "pt_15cb04cd4b34536fe3e4b770e7338557" # sign up at https://www.soopr.co to get your publish token and personalize share and reaction options

highlighter: rouge

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-sitemap

whitelist:
  - jekyll-redirect-from
